Repository MainfluxLabs/mainflux, pull requests merged in 2025-08, with the labels that each got.

#759 MF-746 - Require e-mail address verification during the self-register flow
  cmd/users/main.go
  docker/.env
  docker/docker-compose.yml
  docker/templates/users.tmpl
  pkg/apiutil/errors.go
  pkg/sdk/go/users.go
  pkg/sdk/go/users_test.go
  users/README.md
  users/api/http/endpoint.go
  users/api/http/endpoint_test.go
  users/api/http/logging.go
  users/api/http/metrics.go
  users/api/http/requests.go
  users/api/http/responses.go
  users/api/http/transport.go
  users/emailer.go
  users/emailer/emailer.go
  users/mocks/email.go
  users/mocks/verifications.go
  users/postgres/README.md
  users/postgres/init.go
  users/postgres/verifications.go
  users/postgres/verifications_test.go
  users/service.go
  users/service_test.go
  users/tracing/verification.go
  users/users.go
Labels: new feature

#776 MF-777 - Refactor building URLs in user-facing e-mails
  cmd/users/main.go
  docker/.env
  docker/docker-compose.yml
  pkg/apiutil/errors.go
  pkg/apiutil/transport.go
  pkg/sdk/go/users.go
  users/README.md
  users/api/http/endpoint.go
  users/api/http/endpoint_test.go
  users/api/http/logging.go
  users/api/http/metrics.go
  users/api/http/requests.go
  users/api/http/transport.go
  users/emailer.go
  users/emailer/emailer.go
  users/mocks/email.go
  users/service.go
Labels: refactor

#791 Update OpenAPI definitions for self-register and e-mail verification HTTP API endpoints
  api/openapi/users.yml
Labels: documentation

#793 MF-790 - Asynchronously send e-mails from service methods
  cmd/users/main.go
  users/emailer/logging.go
  users/emailer/metrics.go
  users/service.go
Labels: enhancement

#792 MF-788 - Standardize messages API
  readers/api/endpoint.go
  readers/api/endpoint_test.go
  readers/api/logging.go
  readers/api/metrics.go
  readers/api/requests.go
  readers/api/transport.go
  readers/messages.go
  readers/mocks/messages.go
  readers/mongodb/messages.go
  readers/mongodb/messages_test.go
  readers/postgres/messages.go
  readers/postgres/messages_test.go
  readers/timescale/messages.go
  readers/timescale/messages_test.go
Labels: enhancement, refactor
